Ensure GitHub is

diff --git a/.github/workflows/wordpress.yml b/.github/workflows/wordpress.yml
--- a/.github/workflows/wordpress.yml
+++ b/.github/workflows/wordpress.yml
@@ -3,7 +3,7 @@ name: Deploy Plugin
 on:
   push:
     tags:
-      - '*'
+      - '*.*.*'
   pull_request:
     branches:
       - master
@@ -26,7 +26,7 @@ jobs:
       - uses: actions/checkout@main
 
       - name: Install Node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
           node-version: '18'
 
@@ -55,7 +55,7 @@ jobs:
   release:
     name: Deploy WordPress.org
     needs: status-check
-    if: contains(github.ref, 'tags/')
+    if: contains(github.ref, 'refs/tags/')
     runs-on: ubuntu-latest
     environment:
       name: production
@@ -63,6 +63,21 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@main
+        with:
+          fetch-depth: 0
+
+      - name: Fail if tagged commit is not in master branch
+        run: |
+          BRANCHES=$(git branch --contains ${{ github.ref_name }})
+          echo "Tagged commit exists in branches: $BRANCHES"
+          for BRANCH in $BRANCHES ; do
+            if [[ "$BRANCH" == "master" ]]; then
+              echo "✅ The tag belongs to the master branch."
+              exit 0
+            fi
+          done
+          echo "❌ Error: The tag is not on the master branch. Deployment aborted."
+          exit 1
 
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
@@ -73,7 +88,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Install Node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
           node-version: '18'
 
